In [3]:
import pandas as pd

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [7]:
df = pd.read_csv('500hits (1).csv', encoding = 'latin-1')

In [8]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [9]:
df = df.drop(columns = ['PLAYER', 'CS'])

In [10]:
df.head(
    
)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,0.329,1

In [11]:
X = df.iloc[:, 0:13]
y = df.iloc[:,13]

In [12]:
print(X)

     YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 11, test_size = 0.2)

In [14]:
scaler = MinMaxScaler(feature_range= (0,1))

In [15]:
X_train = scaler.fit_transform(X_train)

In [16]:
X_test = scaler.fit_transform(X_test)

In [17]:
print(X_train)

[[0.46666667 0.35255438 0.31382907 ... 0.67820248 0.00929235 0.225     ]
 [0.13333333 0.25543753 0.24989842 ... 0.18595041 0.17155111 0.38333333]
 [0.2        0.23672231 0.18854124 ... 0.32386364 0.02144389 0.375     ]
 ...
 [0.46666667 0.32169954 0.32263308 ... 0.13429752 0.18656183 0.64166667]
 [0.53333333 0.58523015 0.50684004 ... 0.61260331 0.22444603 0.175     ]
 [0.2        0.21041983 0.16402546 ... 0.41219008 0.02144389 0.3       ]]

In [18]:
print(X_test)

[[0.5        0.33425224 0.10288675 ... 0.10147173 0.02853261 0.35869565]
 [0.5        0.44727774 0.30662472 ... 0.38652208 0.06929348 0.32608696]
 [0.28571429 0.452102   0.51720947 ... 0.12083656 0.4986413  1.        ]
 ...
 [0.42857143 0.31219848 0.15173945 ... 0.17893106 0.04076087 0.40217391]
 [0.35714286 0.47553411 0.50943745 ... 0.54531371 0.06793478 0.54347826]
 [0.57142857 0.69676085 0.67246484 ... 0.21068939 0.26766304 0.75      ]]

In [20]:
knn = KNeighborsClassifier(n_neighbors= 8)

In [21]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [22]:
y_pred = knn.predict(X_test)

In [23]:
print(y_pred)

[0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0
 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1]

In [24]:
knn.score(X_test,y_test)

0.8279569892473119

In [25]:
cm = confusion_matrix(y_test, y_pred)

In [26]:
print(cm)

[[55 12]
 [ 4 22]]

In [27]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.93      0.82      0.87        67
           1       0.65      0.85      0.73        26

    accuracy                           0.83        93
   macro avg       0.79      0.83      0.80        93
weighted avg       0.85      0.83      0.83        93

In [28]:
print(knn.n_samples_fit_)

372